const List<String> paises = [
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Angola',
  'Antigua e Barbuda',
  'Arábia Saudita',
  'Argélia',
  'Argentina',
  'Armênia',
  'Austrália',
  'Áustria',
  'Azerbaijão',
  'Bahamas',
  'Bahrein',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Bélgica',
  'Belize',
  'Benin',
  'Bermudas',
  'Bolívia',
  'Bósnia e Herzegovina',
  'Botsuana',
  'Brunei',
  'Bulgária',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Camarões',
  'Camboja',
  'Canadá',
  'Cazaquistão',
  'Catar',
  'Centro-Africana',
  'Chade',
  'Chile',
  'China',
  'Chipre',
  'Cingapura',
  'Cidade do Vaticano',
  'Colômbia',
  'Comores',
  'Congo',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa do Marfim',
  'Costa Rica',
  'Croácia',
  'Cuba',
  'Dinamarca',
  'Djibouti',
  'Dominica',
  'Egito',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eritreia',
  'Eslováquia',
  'Eslovênia',
  'Espanha',
  'Estados Unidos',
  'Estônia',
  'Etiópia',
  'Fiji',
  'Filipinas',
  'Finlândia',
  'França',
  'Gabão',
  'Gâmbia',
  'Gana',
  'Geórgia',
  'Granada',
  'Grécia',
  'Guatemala',
  'Guiana',
  'Guiné',
  'Guiné Equatorial',
  'Guiné-Bissau',
  'Haiti',
  'Honduras',
  'Hungria',
  'Ilhas Marshall',
  'Ilhas Salomão',
  'Índia',
  'Indonésia',
  'Irã',
  'Iraque',
  'Irlanda',
  'Islândia',
  'Israel',
  'Itália',
  'Jamaica',
  'Japão',
  'Jordânia',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letônia',
  'Líbano',
  'Libéria',
  'Líbia',
  'Liechtenstein',
  'Lituânia',
  'Luxemburgo',
  'Macedônia do Norte',
  'Madagascar',
  'Malásia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marrocos',
  'Mauritânia',
  'Maurício',
  'México',
  'Micronésia',
  'Moçambique',
  'Moldávia',
  'Mônaco',
  'Mongólia',
  'Montenegro',
  'Marrocos',
  'Myanmar (Birmânia)',
  'Namíbia',
  'Nauru',
  'Nepal',
  'Nicarágua',
  'Níger',
  'Nigéria',
  'Noruega',
  'Nova Zelândia',
  'Omã',
  'Países Baixos (Holanda)',
  'Palestina',
  'Paquistão',
  'Palau',
  'Panamá',
  'Papua Nova Guiné',
  'Paraguai',
  'Peru',
  'Polônia',
  'Portugal',
  'Quênia',
  'Quirguistão',
  'Reino Unido',
  'República Dominicana',
  'República Tcheca',
  'Romênia',
  'Ruanda',
  'Rússia',
  'Ruanda',
  'Samoa',
  'San Marino',
  'Santa Lúcia',
  'São Cristóvão e Névis',
  'São Tomé e Príncipe',
  'Senegal',
  'Serra Leoa',
  'Seychelles',
  'Singapura',
  'Síria',
  'Sri Lanka',
  'Suécia',
  'Suíça',
  'Suriname',
  'Essuatíni'
      'Tailândia',
  'Tajikistan',
  'Tanzânia',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad e Tobago',
  'Tunísia',
  'Turcomenistão',
  'Turquia',
  'Tuvalu',
  'Ucrânia',
  'Uganda',
  'Uruguai',
  'Uzbequistão',
  'Vanuatu',
  'Venezuela',
  'Vietnã',
  'Yemen',
  'Zâmbia',
  'Zimbábue',
];
